name: deploy to ecs
on:
  push:
    branches:
      - main
env:
  DOCKER_NAME: py_web3_server
  SRC_PATH: /home/deploy/py_web3_server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump context
        env:
          CONTEXT: ${{ secrets.REMOTE_USER }}
        run: echo "$CONTEXT"
      # 切换分支
      - name: Checkout
        uses: actions/checkout@v3
        
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}

      - name: restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: docker restart ${{ env.DOCKER_NAME }}
